services:
  evaluate-agent:
    build: .
    volumes:
      - ../data:/app/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    environment:
      - WEIGHT_ENERGY=${WEIGHT_ENERGY:-0.76}
      - WEIGHT_COMFORT_NOW=${WEIGHT_COMFORT_NOW:-0.14}
      - WEIGHT_COMFORT_FUTURE=${WEIGHT_COMFORT_FUTURE:-0.10}
