services:
  lstm-training:
    build: .
    volumes:
      - ../data:/app/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
